### ISSUE TITLE
[BUG] Input audio resampling is not efficiently implemented

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/neon-iris#28]
### Description

Input audio resampling is not efficiently implemented here. Consider pulling the implementation from ovos-stt-http-server or using helpers from neon_utils.file_utils

### Steps to Reproduce

- Record voice in Gradio interface
- Press Submit to send to Neon
- Wait 15-16+ seconds for the audio to convert and everything to process

**Comment by NeonDaniel** [comment]
It may be better to skip the resampling here and add it to `neon-speech` so we can handle other clients that may not have sufficient processing power to do any conversion.
